/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels.magazines;

import Panels.magazine;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import static java.awt.SystemColor.menu;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.KeyStroke;

/**
 *
 * @author Karolis
 */
public class magazineMenu extends javax.swing.JPanel {

    private final GridBagConstraints gridBagConstraints;

    /**
     * Creates new form magazineMenu
     */
    public magazineMenu() {
        initComponents();
     
        
        JMenuItem menuItem;
        JRadioButtonMenuItem rbMenuItem;
        JCheckBoxMenuItem cbMenuItem;

        BackgroundMenuBar menuBar = new BackgroundMenuBar();
        menuBar.setColor(new Color(234,234,234));
        
        JMenu menu = new JMenu("Visi gamybos žurnalai");
        JMenu menu2 = new JMenu("Naujas gamybos žurnalas");
        menu.setFont(new java.awt.Font("Segoe UI", 0, 14));
        menu2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        
        menuBar.add(menu);
        menuBar.add(menu2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        add(menuBar, gridBagConstraints);
        
        menu.addMouseListener(new MouseAdapter() {
             public void mousePressed(MouseEvent e) {
                loadmenu(1);
        }});
        
        menu2.addMouseListener(new MouseAdapter() {
             public void mousePressed(MouseEvent e) {
                loadmenu(2);
        }});
        
    }
    
    public void loadmenu(int meeded){
        magazine.refresh(meeded);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(234, 234, 234));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
