/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Main.MysqlConnect;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.ListModel;
import java.awt.Color;
/**
 *
 * @author Karolis
 */
public class invOptions extends javax.swing.JPanel {
 
    /**
     * Creates new form invOptions
     */
    public invOptions() {
        initComponents();
        AllSeries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInvNewSerie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jInvNumFormat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSeries = new javax.swing.JList<>();
        jInvNumLast = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nustatymai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Serija:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Pridėti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Formatas:");

        jListSeries.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jListSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSeriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListSeries);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Numeris:");

        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setText("Valyti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jInvNumFormat)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jInvNewSerie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInvNumLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jInvNewSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInvNumFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jInvNumLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 426, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String newserie = jInvNewSerie.getText();
        String numformat = jInvNumFormat.getText();
        
        try {
            Statement st = MysqlConnect.connect().createStatement(); 
            ResultSet res = st.executeQuery("SELECT * FROM  dm_invoice_serie WHERE serie LIKE '"+newserie+"'");
            if(newserie != null && numformat != null && !res.next()){            
                 
            st.executeUpdate("INSERT INTO dm_invoice_serie (serie,number,last_number) VALUES ('"+newserie+"', '"+numformat+"', '1')");
 
            jInvNewSerie.setText(null);
            jInvNumFormat.setText(null); 
            
            AllSeries();
            }else{
                String numlast = jInvNumLast.getText();
                st.executeUpdate("UPDATE dm_invoice_serie SET number = '"+numformat+"', last_number = '"+numlast+"' WHERE serie LIKE '"+newserie+"' ");
            jInvNewSerie.setText(null);
            jInvNumFormat.setText(null);
            jInvNumLast.setText(null); 
            jButton1.setText("Pridėti");
                AllSeries();
            }
        } catch (SQLException e) {
        } finally {
            //mysqlConnect.disconnect();      
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSeriesMouseClicked
        String selected = jListSeries.getSelectedValue();
        String[] split = selected.split(" ");
        int split1 = Integer.parseInt(split[1]);
        int split2 = Integer.parseInt(split[2]);
        
        String split1String = split1 + "";
        String split2String = split2 + "";
        
//check or exists
        

        try {
            Statement st = MysqlConnect.connect().createStatement(); 
            ResultSet res = st.executeQuery("SELECT * FROM  dm_invoice_serie WHERE serie LIKE '"+split[0]+"'");
            if(res.next()){
                jInvNewSerie.setEditable(false);
                jInvNewSerie.setBackground(new Color(225, 225, 225));
                jButton1.setText("Atnaujinti");
                jInvNewSerie.setText(split[0]);  
                jInvNumFormat.setText(split2String);
                jInvNumLast.setText(split1String); 
            }else{
                jInvNewSerie.setEditable(true);
                jInvNewSerie.setBackground(new Color(255, 255, 255));
                jButton1.setText("Pridėti");
                jInvNewSerie.setText(null);  
                jInvNumFormat.setText(null);
                jInvNumLast.setText(null); 
            }
        } catch (SQLException e) {
        } finally {
            //mysqlConnect.disconnect();      
        }
        
        
  
      
    }//GEN-LAST:event_jListSeriesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jInvNewSerie.setEditable(true);
        jInvNewSerie.setBackground(new Color(255, 255, 255));
        jButton1.setText("Pridėti");
        jInvNewSerie.setText(null);  
        jInvNumFormat.setText(null);
        jInvNumLast.setText(null); 
        AllSeries();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jInvNewSerie;
    private javax.swing.JTextField jInvNumFormat;
    private javax.swing.JTextField jInvNumLast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListSeries;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    //get All invoice series and update list
    private void AllSeries(){
        
        try {
            Statement st = MysqlConnect.connect().createStatement();
            ResultSet res = st.executeQuery("SELECT * FROM  dm_invoice_serie");
            
            DefaultListModel <String> dlm = new DefaultListModel<>();
            while (res.next()) {
        
                int last_number = res.getInt("last_number");
                int nr = res.getInt("number");
                String serie = res.getString("serie");
                String numberAsString = String.format("%0"+nr+"d%s",0 , last_number);

                dlm.addElement(serie+' '+numberAsString+' '+res.getInt("number"));
            }
            
            jListSeries.setModel(dlm);
            
        } catch (SQLException e) {
        } finally {
            //mysqlConnect.disconnect();
             
        }
    }
    
}
