/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import Classes.EXhelper;
import Models.Product;
import Classes.WarehouseClass;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
 
/**
 *
 * @author Karolis
 */
public class warehouseProduct extends javax.swing.JPanel {
    private int id_product;
    private String product_name;
    /**
     * Creates new form warehouseProduct
     * @param id
     */
    public warehouseProduct(int id, String name) {
        id_product = id;
        product_name = name;
        initComponents();
        List<Product> result = WarehouseClass.getProduct(id);
        
        TableColumnModel TablePl = jTablePl.getColumnModel();
        TablePl.getColumn(0).setPreferredWidth(80);    
        TablePl.getColumn(1).setPreferredWidth(70);   
        TablePl.getColumn(2).setPreferredWidth(70);    
        TablePl.getColumn(3).setPreferredWidth(70);    
        TablePl.getColumn(4).setPreferredWidth(200);
        TablePl.getColumn(5).setPreferredWidth(0);
        
        jTablePl.getColumnModel().getColumn(5).setWidth(0);
        jTablePl.getColumnModel().getColumn(5).setMinWidth(0);
        jTablePl.getColumnModel().getColumn(5).setMaxWidth(0); 
        
        showName.setText(name);
        jTablePl.getColumnModel().getColumn(3).setCellRenderer(new EXhelper.DecimalFormatRenderer());         

        jTablePl.getModel().addTableModelListener(new TableModelListener() {
            
          public void tableChanged(TableModelEvent e) {
            int index  = jTablePl.getSelectedRow();
            
            if(index != -1){
                DefaultTableModel model = (DefaultTableModel) jTablePl.getModel();
               
                int id_p = (int) model.getValueAt(index, 5);
                String note = (String) model.getValueAt(index, 4);
                String invoice = (String) model.getValueAt(index, 1);
                
                Product product = new Product(id_p);
                product.setInvoice(invoice);
                product.setNote(note);
                product.update(); 
            
            }
          }
          
        }); 
        
        DefaultTableModel model = (DefaultTableModel) jTablePl.getModel();
            
            while (model.getRowCount() > 0) {
                    model.removeRow(0);
            }
            
 
        
        for(Product nn : result) {
       
            Object[] row = {nn.getDate(), nn.getInvoice(), nn.getBalance_left(), nn.getBalance(), nn.getNote(), nn.getID()};
            model.addRow(row);
             
        
        }
            
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLoadedID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        showName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        showName.setText("Likučiai");

        jTablePl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Sąskaita", "Likutis", "Pridėta", "Pastaba", "#ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePl);

        jButton1.setText("Pridėti");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLoadedID.setText("#id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLoadedID))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showName)
                    .addComponent(jLoadedID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePlMouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
    
        warehouseAddProduct.getObj(id_product, product_name).setVisible(true);
        
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLoadedID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePl;
    private javax.swing.JLabel showName;
    // End of variables declaration//GEN-END:variables

  
}
